name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin] # Platforms: Linux, Windows, macOS
        goarch: [amd64, arm64] # Architectures: 64-bit, ARM
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/version-parser-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/* # Upload all binaries to the artifact storage

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries # Matches the artifact name in the build job
          path: dist

      - name: List dist directory
        run: ls -al dist # Ensure binaries are downloaded correctly

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/* # Attach all files in the dist directory to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
